config/routes.rb
PhotoShare::Application.routes.draw do
  root to: 'users#home'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :except => [:index, :update, :edit]
  resources :sessions
  resources :photos, :except => :index

end

app/models/article.rb
class Article < ActiveRecord::Base

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "sad_panda.jpg"
  has_and_belongs_to_many :users

  validates :description, presence: true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/session.rb
class Session < ActiveRecord::Base
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "sad_panda.jpg"
  has_and_belongs_to_many :photos

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true,
            case_sensitive: false
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_digest, presence: true, uniqueness: true
  validates_attachment_content_type :avatar,
                                    :content_type => ["image/jpg", "image/gif", "image/png"],
                                    :size => { :in => 0..2.megabytes }
  #validates_attachment_size :size => { :in => 0..10.kilobytes }
  validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize, only: [:edit, :update]
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    current_user.photos << @photo
    if @photo.save
      flash[:notice] = "Your photo has been added!"
      redirect_to photo_path(@photo)
    else
      render 'new'
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end


private

  def photo_params
    params.require(:photo).permit(:description,
                                  :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Logged in!"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user.avatar = nil
    @user.save
  end

private

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation,
                                 :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer navbar navbar-fixed-bottom">
  <div class="container">

  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header navbar navbar-fixed-top">
  <div class="container-inner">
    <ul class="brand pull-left">
      <li><%= link_to "Photastic", root_path %></li>
    </ul>
    <ul class="header-links pull-right">
      <% if current_user %>
        <li>Logged in as <span class="purple"><%= link_to current_user.email, user_path(current_user) %></span></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign In", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title)+" | Photastic" : "Photastic" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Inder|ABeeZee|Concert+One|Sniglet|Roboto:400,900' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body>

<%= render 'layouts/header' %>

<div class="container flash">
  <span class="green"><%= flash[:notice] %></span>
  <span class="red"><%= flash[:alert] %></span>
</div>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/photos/new.html.erb
<%= content_for(:title, "Add Photo") %>

<div class="add-photo-page container">
  <h1>Add a photo</h1>
  <%= form_for @photo, :url => photos_path, :html => { :multipart => true } do |f| %>
    <% if @photo.errors.any? %>
      <div class="red error_messages">
        <h2>Invalid photo upload</h2>
        <ul>
          <% @photo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :image %><br />
      <%= f.file_field :image %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="actions"><%= f.submit "Add Photo" %></div>
  <% end %>
</div>

app/views/photos/show.html.erb
<div class="photo-page container">

  <%= image_tag @photo.image.url(:medium), class: "user-photo" %>

</div>

app/views/users/home.html.erb
<%= content_for(:title, "Home") %>

<div class="main-page container">
  <h1>Share your Photastic moments</h1>
  <div class="row">
    <div class="photo">
      <%= image_tag("happy_couple.jpg", height: '70%', width: '70%', class: "happy-couple") %>
    </div>
  </div>
  <%= link_to "Sign up for Photastic", signup_path, class: "signup-button btn btn-success" %>
</div>

app/views/users/new.html.erb
<%= content_for(:title, "Sign up") %>

<div class="input-page container">
  <h1>Sign Up</h1>
  <%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
    <% if @user.errors.any? %>
      <div class="red error_messages">
        <h2>Invalid email or password</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, class: 'form-control'  %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class: 'form-control'  %>
    </div>
    <div class="field">
      <%= f.label :avatar %><br />
      <%= f.file_field :avatar %>
    </div>
    <div class="actions"><%= f.submit "Sign Up" %></div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-page container">
  <div class="row">
    <div class="col-md-6 user-left">
      <h1>Welcome <%= @user.email %></h1>

      <%= image_tag @user.avatar.url(:medium), class: "user-avatar" %>
    </div>

    <div class="col-md-6 user-right">
      <%= link_to "Add a new photo!", new_photo_path(@user.photos), class: "btn btn-success" %>

    </div>

  </div>
  <hr>

  <div id="wrapper">
    <div id="list">
      <% current_user.photos.each do |photo| %>
        <div class="item text-center">
          <br />
          <%= image_tag photo.image.url(:medium), class: "pinterist-photo", height: '100%', width: '100%' %>
          <br />
          <%= photo.description %>
        </div>
      <% end %>
    </div>
  </div>

</div>